#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
bin_to_coe.py — conv1x1(cv1/cv2) 가중치 .bin -> .coe 변환
==========================================================
Block Memory Generator의 "Load Init File"에 넣을 .coe 파일을 만듭니다.

conv1x1_stream / conv1x1_cv2_stream 의 weight[OUT_CH][IN_CH] 는
weight_PORTA/PORTB 둘 다 IP 자신이 차지하므로 PS가 런타임에 쓸 수
없습니다 — 대신 비트스트림에 값을 미리 박아 넣습니다.

가정: .bin 파일은 calibrate_model6.py 가 저장한 그대로,
      numpy 기본(C-order) flatten = oc가 바깥, ic가 안쪽 순서.
      즉 파일의 k번째 바이트 = weight[k // IN_CH][k % IN_CH]

사용법
  python bin_to_coe.py --bin calib_out/cv1_weight.bin  --in-ch 128 --out cv1_weight.coe
  python bin_to_coe.py --bin calib_out/cv2_weight.bin  --in-ch 256 --out cv2_weight.coe

★ dtype 주의: calibrate_model6.py 는 가중치 값을 -128~127로 clamp 해두고
  타입은 int32 로 저장합니다 (element당 4바이트). int8로 읽으면 4배
  많은 "원소"로 잘못 해석되어 OUT_CH 계산이 깨집니다 — 이 스크립트는
  기본으로 int32 로 읽고, 값이 실제로 int8 범위 안에 있는지 검증합니다.
"""

import argparse
import numpy as np


def to_twos_complement_bin(v: int, bits: int = 8) -> str:
    """int8 값(-128~127)을 8자리 2의 보수 2진 문자열로."""
    if v < 0:
        v += 1 << bits
    return format(v, f"0{bits}b")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bin", required=True, help="weight .bin 경로")
    ap.add_argument("--in-ch", type=int, required=True, help="IN_CH (cv1=128, cv2=256)")
    ap.add_argument("--out", required=True, help="출력 .coe 경로")
    ap.add_argument("--dtype", default="int32", choices=["int32", "int8"],
                    help="calibrate_model6.py 는 int32 로 저장함 (기본값)")
    args = ap.parse_args()

    np_dtype = np.int32 if args.dtype == "int32" else np.int8
    data = np.fromfile(args.bin, dtype=np_dtype)

    vmin, vmax = int(data.min()), int(data.max())
    if vmin < -128 or vmax > 127:
        raise SystemExit(
            f"[!] 값 범위 {vmin}~{vmax} 가 int8(-128~127)을 벗어남. "
            f"--dtype 을 반대로 바꿔서 다시 시도해보세요."
        )
    print(f"[i] 값 범위 확인: {vmin} ~ {vmax} (int8 정상 범위)")
    total = data.size
    if total % args.in_ch != 0:
        raise SystemExit(
            f"[!] 크기 불일치: {total} 개가 in_ch={args.in_ch} 로 안 나눠떨어짐"
        )
    out_ch = total // args.in_ch
    print(f"[i] {args.bin}: {total} elems -> OUT_CH={out_ch}, IN_CH={args.in_ch}")

    with open(args.out, "w") as f:
        f.write("; conv1x1 weight init file, auto-generated by bin_to_coe.py\n")
        f.write(f"; source = {args.bin}\n")
        f.write(f"; OUT_CH = {out_ch}, IN_CH = {args.in_ch}\n")
        f.write("memory_initialization_radix=2;\n")
        f.write("memory_initialization_vector=\n")

        lines = [to_twos_complement_bin(int(v)) for v in data]
        f.write(",\n".join(lines))
        f.write(";\n")

    print(f"[OK] {args.out} ({len(lines)} words, 8bit each)")
    print("[i] Block Memory Generator 설정: Load Init File 체크 -> 이 .coe 지정")
    print("    Memory Type=True Dual Port RAM, Port A/B Width=8, "
          f"Depth={total}")


if __name__ == "__main__":
    main()
