#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
bin_to_coe_float.py — float32 bram 배열(bn_scale 등) -> .coe
================================================================
conv 계열(int8)과 다르게, float는 2의 보수 변환이 아니라 IEEE754
비트 패턴을 그대로 32bit 이진수로 박아넣습니다. 값이 실행 중 절대
안 바뀌는 계산된 상수라, conv1x1/conv3x3와 같은 이유로 PS 런타임
쓰기 없이 .coe로 초기화합니다.

여러 세트를 이어붙일 수 있습니다 (N_SET 차원이 있는 bn_scale[N_SET][CH]
같은 배열용). 세트 순서는 call_counter 순서(m0.cv1=0, m0.cv2=1, ...)와
반드시 일치해야 합니다.

사용법
  # bn_scale (4벌, bn_silu_64용)
  python bin_to_coe_float.py \
      --bins calib_out/m0_cv1_bn_scale.bin calib_out/m0_cv2_bn_scale.bin \
             calib_out/m1_cv1_bn_scale.bin calib_out/m1_cv2_bn_scale.bin \
      --out bn64_bn_scale.coe

  # output_scale 처럼 세트당 원소 1개(스칼라)짜리도 같은 방식
  python bin_to_coe_float.py \
      --bins calib_out/m0_cv1_output_scale.bin ... \
      --out bn64_output_scale.coe
"""

import argparse
import struct

import numpy as np


def float32_to_bin32(v: float) -> str:
    """IEEE754 32bit 비트 패턴을 그대로 32자리 이진 문자열로."""
    packed = struct.pack(">f", v)          # big-endian 4바이트
    as_uint = struct.unpack(">I", packed)[0]
    return format(as_uint, "032b")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bins", nargs="+", required=True,
                    help="순서대로 이어붙일 float32 .bin 파일들 (call_counter 순서와 일치)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    all_data = []
    for path in args.bins:
        d = np.fromfile(path, dtype=np.float32)
        print(f"[i] {path} -> {d.size} elems, sample={d[:3]}")
        all_data.append(d)

    sizes = {d.size for d in all_data}
    per_set = sizes.pop() if len(sizes) == 1 else None
    if per_set is None:
        print(f"[!] 주의: 파일별 크기가 다름 {[d.size for d in all_data]} "
              f"— 그래도 순서대로 이어붙입니다")

    with open(args.out, "w") as f:
        f.write("; float32 bram init file, auto-generated by bin_to_coe_float.py\n")
        f.write(f"; sources (순서대로) = {args.bins}\n")
        f.write("memory_initialization_radix=2;\n")
        f.write("memory_initialization_vector=\n")

        lines = []
        for d in all_data:
            lines.extend(float32_to_bin32(float(v)) for v in d)
        f.write(",\n".join(lines))
        f.write(";\n")

    print(f"[OK] {args.out} ({len(lines)} words, 32bit each)")
    print(f"[i] Block Memory Generator 설정: Stand-Alone, Width=32, Depth={len(lines)}, "
          "Load Init File 체크 -> 이 .coe 지정")


if __name__ == "__main__":
    main()