from __future__ import annotations

import argparse
from pathlib import Path

from ppe_verify.io_utils import load_results, save_results
from ppe_verify.metrics import compare_suite
from ppe_verify.mock_data import golden_frames, mock_dut_frames
from ppe_verify.report import render_report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare PPE golden and DUT detections")
    parser.add_argument(
        "--mode",
        choices=("mock-pass", "mock-fail"),
        default="mock-pass",
        help="run a dependency-free demonstration when JSON paths are omitted",
    )
    parser.add_argument("--golden", type=Path, help="golden JSON generated by YOLO")
    parser.add_argument("--actual", type=Path, help="DUT/FPGA JSON in the same schema")
    parser.add_argument("--iou", type=float, default=0.50)
    parser.add_argument("--confidence-tolerance", type=float, default=0.10)
    parser.add_argument(
        "--write-demo-artifacts",
        action="store_true",
        help="save mock golden/actual JSON under artifacts/",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if (args.golden is None) != (args.actual is None):
        raise SystemExit("--golden and --actual must be supplied together")

    if args.golden is not None:
        expected = load_results(args.golden)
        actual = load_results(args.actual)
    else:
        expected = golden_frames()
        actual = mock_dut_frames(inject_fault=args.mode == "mock-fail")
        if args.write_demo_artifacts:
            save_results("artifacts/mock_golden.json", expected)
            save_results("artifacts/mock_actual.json", actual)

    comparison = compare_suite(
        expected,
        actual,
        iou_threshold=args.iou,
        confidence_tolerance=args.confidence_tolerance,
    )
    print(render_report(comparison))
    return 0 if comparison.passed else 1


if __name__ == "__main__":
    raise SystemExit(main())

