// auto-generated by calibrate_model6.py
#ifndef MODEL6_PARAMS_H
#define MODEL6_PARAMS_H

#define S_IN           0.0389917693f
#define S_CV1OUT       0.0535092177f
#define S_M0CV1        0.0387180487f
#define S_M0CV2        0.0338272338f
#define S_Y2           0.0386524918f
#define S_M1CV1        0.0344310327f
#define S_M1CV2        0.0658926708f
#define S_Y3           0.0645476729f
#define S_CAT          0.0553356526f
#define S_OUT          0.0386474579f

#define WSCALE_CV1        0.0029566006f
#define WSCALE_M0_CV1     0.0029027744f
#define WSCALE_M0_CV2     0.0022510919f
#define WSCALE_M1_CV1     0.0021741972f
#define WSCALE_M1_CV2     0.0040446604f
#define WSCALE_CV2        0.0039158618f

#endif
